name: GitHub-Profile-Summary-Cards

on:
  schedule:
    # Executa a cada 24 horas (meia-noite UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite rodar o script manualmente clicando em um botão

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write # Dá permissão para a Action salvar as imagens no repositório
    
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}